#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event1 c 13 65"
export BOOTREC_EVENT="/dev/input/event1"
export BOOTREC_LED_RED="/sys/class/leds/red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/blue/brightness"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p18 b 181 18"
export BOOTREC_FOTA="/dev/block/mmcblk0p18"
